FROM eclipse-temurin:17-jdk-jammy

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends iproute2 curl && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY app/build/install/app/ .

ENTRYPOINT ["bin/app"]